uridecodebin:
  #uri: file://chunks/inf.mp4
  uri: file://videos/2.mp4
 
streammux:
  batch-size: 1
  width: 3840
  height: 2160
  live-source: 0
  enable-padding: 0
  nvbuf-memory-type: 0
  attach-sys-ts: 1


nvinfer:
  config-file-path: ./config_infer_primary_yoloV8.txt
  gpu-id: 0
  #nvbuf-memory-type: 0
  batch-size: 2
  input-tensor-meta: 1

nvtracker:
  tracker-width: 832
  tracker-height: 832
  ll-lib-file: /opt/nvidia/deepstream/deepstream-6.2/lib/libnvds_nvmultiobjecttracker.so
  ll-config-file: /opt/nvidia/deepstream/deepstream-6.2/sources/DeepStream-Yolo/config_tracker_NvDCF_perf.yml
  gpu-id: 0
  enable-batch-process: 1
  enable-past-frame: 1
  display-tracking-id: 1
  compute-hw: 1



filesink:
  location: output.mp4
  sync: 0
  